### ISSUE TITLE
the debug says 0.1.8 when I have removed and installed 0.19 and rerun the install

### ISSUE THREAD

**Issue by sidonsoft** [chrisrude/oobabot-plugin#8]
2023-06-01 01:14:51,965 DEBUG oobabot_plugin: inside Oobabooga, using script.py version: 0.1.8
2023-06-01 01:14:51,966 DEBUG oobabot_plugin version: 0.1.8
2023-06-01 01:14:51,966 DEBUG oobabot version: 0.1.9

**Comment by chrisrude** [comment]
That's my bad!  I forgot to update the version number inside the plugin module when I published 0.1.9.  If you see the yaml editor you have 0.1.9.  Will be fixed in the next one.  Thanks for mentioning it!

**Comment by chrisrude** [comment]
This should be fixed with the 0.2.0 release.  Please let me know if it still occurs after that.

To upgrade, just go into your textgen directory / conda environment and run `pip install oobabot-plugin --upgrade`.

Note that the `script.py` version WILL still report 0.1.8, as that is versioned separately.  As long as the other versions are 0.2.0, things are good.
